### ISSUE TITLE
_safe_print_argument in command.py

### ISSUE THREAD

**Issue by biell** [StamKaly/altitude-mod-for-TBG#2]
I believe that you also need to protect against "\" characters.  I ran  into this with player nicknames.  Originally, some of my code didn't work for Apache, because his nickname is "/* Apache *\", and that trailing backslash got me.  He wasn't receiving whisper messages, and a number of other issues.

I believe, that if someone not from TBG joins the server with a "\" in their nick, you will not be able to kick them, as the code stands.  Maybe you can change your search string from ' "' to '\ "' and that will be sufficient?  Also, I don't know if a tab character could ever be inside an argument, but you may need to escape that too.  Maybe '\ \t"' will work, you would have to test it.  Also, double check a single quote ', and a back-tick `.  When I wrote my function, I protected them.  I hope I had a reason to.

This function seems similar to my "altiquote".  I put quotes around arguments with spaces or tabs, but either method works just as well.  https://github.com/biell/alti-server/blob/master/alti%2Bserver#L3361

If you don't think this is an issue, just close it. I am just trying to help.

**Comment by MagneticDuck** [comment]
Indeed, this is an issue. Just fixed the escaping of backslashes. It seems like single-quote are interpreted literally by the altitude server, and as for tabs ... let's just leave that as a little bonus for people who reverse-engineer / memscan the client ^^.

**Comment by biell** [comment]
I think you have it backwards.  You want to search out back slashes (\) first and replace them.  Then, you can do the double quotes (").  I'm not great with python, but I believe both python2 and python3 follow standard object call semantics.  The way you have it, you will be escaping the backslashes you put in front of your quotes.

So, the string '\foo"bar' should become '\\foo\"bar', but will actually become '\\foo\\"bar' due to both replaces acting in serial on what started out as just a double quote (").  I think it should be:

arg.replace('\\', '\\\\').replace('"', '\\"')
